// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pncrzqnwwuwepbzhoptb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuY3J6cW53d3V3ZXBiemhvcHRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxOTU4OTcsImV4cCI6MjA2NTc3MTg5N30.1Cl4S8EHgXn4d2VimDvui-XSjv70keTeDv3n4YG2uXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});